name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # runs daily at 18:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push generated SVGs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/*.svg
          git commit -m "Update 3D contrib graphs" || echo "No changes"
          git push
