name: Generate 3D Profile (Light & Dark)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # Daily at 18:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: .github/settings/github-profile-3d-contrib.json

      - name: Push SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
